### ISSUE TITLE
Compatibility with Nanoc 4

### ISSUE THREAD

**Issue by lifepillar** [nanoc/nanoc-external#4]
It seems to me that this does not need any change to work with Nanoc 4 (but I haven't tried). Is it correct? Also, should this be moved to [Nanoc 4.0](https://github.com/nanoc-4)?

**Comment by ddfreyne** [comment]
@lifepillar So sorry for letting this lie around for so long. I’ve published it to Rubygems. To give you RubyGems push access, I need your e-mail address; can you send it to the address below?

```
echo ZGVuaXMuZGVmcmV5bmVAc3RvbmVzaGlwLm9yZwo= | base64 -d
```
